[package]
name = "pmj-examples"
version = "0.1.0"
authors = ["Simon Brown <si@sjbrown.co.uk>"]
edition = "2018"
publish = false

[dependencies]
pmj = { path = "../pmj" }
rand = { version = "0.8.5", features = ["small_rng"] }
